name: doctorx
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.5
  shared_preferences: ^2.0.8
  image_picker: ^1.0.7
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^24.1.41
  path_provider: ^2.1.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  cached_network_image: ^3.3.0 # Profil fotoğraflarını önbellekleme için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.10

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/reports/
    - assets/reports/kan_tahlili.pdf
    - assets/default_profile.png

flutter_intl:
  enabled: true
